### ISSUE TITLE
What are our "tools of quality"?

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#17]
We should define a set of tools and practices that we view as a minimum to help ensure quality in our work.

F.ex.: CI/CD, issue tracking, a Slack channel, documented roles and responsibilities etc.

**Comment by Reasonable-Solutions** [comment]
So, as for CI, i'd be happy to do full buy in on the vsts-ci.yml builds, for the projects where that is applicable. one project for example, would be travis on $projectname-github, whereas another project would be a vsts build. I hope that a .zip of the build (as you did on yet another project) is sufficient for the rest of the org though. 

as for CD, that's slightly trickier since we would ideally want to have different configurations, in the react based apps that's not so hard but i wouldn't know where to start with gulp. 
However. if the back-end is deployed, and useable, i wouldn't hesitate to just pipe it over to zeit.co/now
 
I was going to bring this up on friday but forgot. Given that our team is small and given that we do not (mostly) track non-feature issues at all. how about we make a vsts project for all the frontend projects where issues will have to start with, e.g. `[$projectname] refactor global state objects`. This would give us one location to point to and at the same time give more visibility to common issues.
